name: Send notification to Telegram
on:
  release:
    types: [ released ]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        uses: appleboy/telegram-action@v1.0.1
        with:
          format: markdown
          disable_web_page_preview: true
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            [Версия ${{ github.event.release.tag_name }}](${{ github.event.release.html_url }})
            
            ${{ github.event.release.body }}
            
            #update #nfqws
